# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-19 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_logo',
            field=models.CharField(default='https://www.google.co.in/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0ahUKEwim0pGi7MnUAhXKvI8KHWi0DLAQjRwIBw&url=https%3A%2F%2Fwww.youtube.com%2Fchannel%2FUCqVDpXKLmKeBU_yyt_QkItQ%2Fvideos&psig=AFQjCNGfwP4z8CyBABcwK5UAN5ojQsPKig&ust=1497959514104611', max_length=1000),
        ),
    ]
